export const ACTION = {
    CLOSE: 'CLOSE_OPEN_CONNECTION',
    CONNECT: 'OPEN_NEW_CONNECTION',
    CHANGE_SUBSCRIPTION: 'CHANGE_SUBSCRIPTION'
};

export const MESSAGE = {
    CONNECTED: 'CONNECTION_OPENED',
    CLOSED: 'CONNECTION_CLOSED',
    UPDATE: 'UPDATED_INFO',
    SUBSCRIPTION_CHANGED: 'SUBSCRIPTION_CHANGED',
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    ACTION_ERROR: 'ACTION_ERROR'
};
